name: Auto Open Pull Request

on:
  push:
    branches-ignore:
      - main
      - "dependabot/**"

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch info
        id: vars
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          SAFE_TITLE=$(echo "$BRANCH" | sed 's/[-_]/ /g' | sed 's/^\(.*\)$/\U\1/')
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "title=$SAFE_TITLE" >> $GITHUB_OUTPUT

      - name: Check if PR exists
        id: findpr
        run: |
          branch="${{ steps.vars.outputs.branch }}"
          existing=$(gh pr list --head "$branch" --json number --jq '.[0].number' || true)
          echo "existing_pr=$existing" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR if missing
        if: steps.findpr.outputs.existing_pr == ''
        run: |
          branch="${{ steps.vars.outputs.branch }}"
          title="${{ steps.vars.outputs.title }}: Automated PR"
          body="Automated PR for branch: $branch\n\nThis PR was opened automatically. Update the description as needed."
          gh pr create --base main --head "$branch" --title "$title" --body "$body" --assignee "jaysonharper"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment existing PR
        if: steps.findpr.outputs.existing_pr != ''
        run: |
          num="${{ steps.findpr.outputs.existing_pr }}"
            gh pr comment "$num" --body "Push detected (branch updated). Workflow confirmed PR #$num still open."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure assignee present
        run: |
          branch="${{ steps.vars.outputs.branch }}"
          num=$(gh pr list --head "$branch" --json number --jq '.[0].number')
          if [ -n "$num" ]; then
            gh pr edit "$num" --add-assignee "jaysonharper"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
