name: Auto Open Pull Request

on:
  push:
    branches-ignore:
      - main
      - "dependabot/**"

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch info
        id: vars
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          SAFE_TITLE=$(echo "$BRANCH" | sed 's/[-_]/ /g' | sed 's/^\(.*\)$/\U\1/')
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "title=$SAFE_TITLE" >> $GITHUB_OUTPUT

      - name: Check if PR exists
        id: findpr
        run: |
          branch="${{ steps.vars.outputs.branch }}"
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          resp=$(curl -sS \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$owner/$repo/pulls?head=${{ github.repository_owner }}:$branch&state=open&per_page=1")
          existing=$(echo "$resp" | jq -r '.[0].number // empty')
          echo "existing_pr=$existing" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR if missing
        if: steps.findpr.outputs.existing_pr == ''
        run: |
          branch="${{ steps.vars.outputs.branch }}"
          title="${{ steps.vars.outputs.title }}: Automated PR"
          body="Automated PR for branch: $branch\n\nThis PR was opened automatically. Update the description as needed."
          data=$(jq -n \
            --arg title "$title" \
            --arg head "$branch" \
            --arg base "main" \
            --arg body "$body" \
            '{title:$title, head:$head, base:$base, body:$body, maintainer_can_modify:true, draft:false}')
          curl -sS -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls \
            -d "$data"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment existing PR
        if: steps.findpr.outputs.existing_pr != ''
        run: |
          num="${{ steps.findpr.outputs.existing_pr }}"
          data=$(jq -n --arg body "Push detected (branch updated). Workflow confirmed PR #$num still open." '{body:$body}')
          curl -sS -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/$num/comments \
            -d "$data"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure assignee present
        run: |
          branch="${{ steps.vars.outputs.branch }}"
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          num="${{ steps.findpr.outputs.existing_pr }}"
          if [ -z "$num" ]; then
            resp=$(curl -sS \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$owner/$repo/pulls?head=${{ github.repository_owner }}:$branch&state=open&per_page=1")
            num=$(echo "$resp" | jq -r '.[0].number // empty')
          fi
          if [ -n "$num" ]; then
            data=$(jq -n --argjson arr '["jaysonharper"]' '{assignees:$arr}')
            curl -sS -X POST \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/$num/assignees \
              -d '{"assignees":["jaysonharper"]}'
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
